### ISSUE TITLE
.so files cannot be found

### ISSUE THREAD

**Issue by mlangebeeke** [januslo/react-native-sunmi-inner-scanner#11]
Hi Janus,

Great libraries, also the inner-printer, thanks for this! :)

I'm using the Sunmi V2 Pro device and have an issue when scanning. The app crashes 'onScan'. I do get errors that the .so files can't be found, but not sure if that's the issue.

Here's my log, maybe you can have a quick look or give some direction?

Thanks so much!
Marco

```
05-24 12:04:57.825   590   590 I CameraService: CameraService::connect call (PID -1 "com..............", camera ID 0) for HAL version default and Camera API version 1
05-24 12:04:58.447  2201  2476 D clh     : 采集摄像头：com..............
05-24 12:05:03.099 32473 32496 E linker  : "/data/app/com..............-1/lib/arm/libscaninit.so" .dynamic section header was not found
05-24 12:05:03.285 32473 32496 E AndroidRuntime: Process: com.............., PID: 32473
05-24 12:05:03.285 32473 32496 E AndroidRuntime: Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com..............-1/lib/arm/libscaninit.so" .dynamic section header was not found
05-24 12:05:03.287  1306  8020 W ActivityManager:   Force finishing activity com............../.MainActivity
05-24 12:05:03.403  2201  2201 I clh     : packageName:Process: com..............
05-24 12:05:03.403  2201  2201 I clh     : Package: com.............. v6 (0.1.5)
05-24 12:05:03.403  2201  2201 I clh     : Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com..............-1/lib/arm/libscaninit.so" .dynamic section header was not found
05-24 12:05:03.403  2201  2201 I clh     : packageName:com..............
05-24 12:05:10.963  1306  8020 I ActivityManager: Killing 32473:com............../u0a144 (adj 900): crash
```

**Comment by mlangebeeke** [comment]
Have some extra logging that shows more detailed where the issue occurs:

```
05-24 12:24:39.117  2531  2564 E AndroidRuntime: Process: com................, PID: 2531
05-24 12:24:39.117  2531  2564 E AndroidRuntime: Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/**com................-1**/lib/arm/libscaninit.so" .dynamic section header was not found
05-24 12:24:39.117  2531  2564 E AndroidRuntime: 	at com.sunmi.scan.Symbol.<clinit>(Unknown Source)
05-24 12:24:39.117  2531  2564 E AndroidRuntime: 	at com.sunmi.scan.SymbolSet.iterator(Unknown Source)
05-24 12:24:39.117  2531  2564 E AndroidRuntime: 	at com.sunmi.scanner.SunmiInnerScannerView$AsyncDecode.doInBackground(SunmiInnerScannerView.java:186)
05-24 12:24:39.117  2531  2564 E AndroidRuntime: 	at com.sunmi.scanner.SunmiInnerScannerView$AsyncDecode.doInBackground(SunmiInnerScannerView.java:168)
05-24 12:24:39.121  1306  2250 W ActivityManager:   Force finishing activity com................/.MainActivity
05-24 12:24:39.222  2201  2201 I clh     : packageName:Process: com................
05-24 12:24:39.222  2201  2201 I clh     : Package: com................ v6 (0.1.5)
05-24 12:24:39.222  2201  2201 I clh     : Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com................-1/lib/arm/libscaninit.so" .dynamic section header was not found
05-24 12:24:39.222  2201  2201 I clh     : 	at com.sunmi.scan.Symbol.<clinit>(Unknown Source)
05-24 12:24:39.222  2201  2201 I clh     : 	at com.sunmi.scan.SymbolSet.iterator(Unknown Source)
05-24 12:24:39.222  2201  2201 I clh     : 	at com.sunmi.scanner.SunmiInnerScannerView$AsyncDecode.doInBackground(SunmiInnerScannerView.java:186)
05-24 12:24:39.222  2201  2201 I clh     : 	at com.sunmi.scanner.SunmiInnerScannerView$AsyncDecode.doInBackground(SunmiInnerScannerView.java:168)
05-24 12:24:39.224  2201  2201 I clh     : packageName:com................
05-24 12:24:39.390  1306  1617 I ActivityManager: Process com.sunmi.baseservice:remote (pid 3028) has died

```
Looks like it does have to with the .so file that can't be found, and it seems to look for it in a folder with my app package name with '-1' added.

Thanks again, would be appreciated if you could have a look.

Marco

**Comment by januslo** [comment]
Not testEd with Sunmi V2 Pro, need the framework information for that
发自我的 iPhone

> 在 2019年5月24日，下午6:14，mlangebeeke <notifications@github.com> 写道：
> 
> Sunmi V2 Pro

**Comment by mlangebeeke** [comment]
Thanks for your quick response!

If you ever have time for this, let me know if I can somehow provide you information on the framework you are referring to.

Marco
