### ISSUE TITLE
Execution failed for task ':app:installDebug'. > com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: Failed to install all

### ISSUE THREAD

**Issue by Mrlonglong** [januslo/react-native-sunmi-inner-scanner#6]
Scanning 615 folders for symlinks in /Users/edz/workspace/react-native/react-native-sunmi-inner-scanner-master/examples/node_modules (14ms)
JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug)...
Download https://jcenter.bintray.com/com/facebook/fresco/fresco/1.0.1/fresco-1.0.1.pom
Download https://jcenter.bintray.com/com/facebook/fresco/imagepipeline-okhttp3/1.0.1/imagepipeline-okhttp3-1.0.1.pom
Download https://jcenter.bintray.com/com/facebook/fresco/drawee/1.0.1/drawee-1.0.1.pom
Download https://jcenter.bintray.com/com/facebook/fresco/fbcore/1.0.1/fbcore-1.0.1.pom
Download https://jcenter.bintray.com/com/facebook/fresco/imagepipeline/1.0.1/imagepipeline-1.0.1.pom
Download https://jcenter.bintray.com/com/facebook/fresco/imagepipeline-base/1.0.1/imagepipeline-base-1.0.1.pom
Download https://jcenter.bintray.com/com/facebook/fresco/fbcore/1.0.1/fbcore-1.0.1.aar
Download https://jcenter.bintray.com/com/facebook/fresco/drawee/1.0.1/drawee-1.0.1.aar
Download https://jcenter.bintray.com/com/facebook/fresco/imagepipeline-base/1.0.1/imagepipeline-base-1.0.1.aar
Download https://jcenter.bintray.com/com/facebook/fresco/imagepipeline/1.0.1/imagepipeline-1.0.1.aar
Download https://jcenter.bintray.com/com/facebook/fresco/fresco/1.0.1/fresco-1.0.1.aar
Download https://jcenter.bintray.com/com/facebook/fresco/imagepipeline-okhttp3/1.0.1/imagepipeline-okhttp3-1.0.1.aar
Incremental java compilation is an incubating feature.
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:react-native-sunmi-inner-scanner:preBuild UP-TO-DATE
:react-native-sunmi-inner-scanner:preReleaseBuild UP-TO-DATE
:react-native-sunmi-inner-scanner:checkReleaseManifest
:react-native-sunmi-inner-scanner:preDebugAndroidTestBuild UP-TO-DATE
:react-native-sunmi-inner-scanner:preDebugBuild UP-TO-DATE
:react-native-sunmi-inner-scanner:preDebugUnitTestBuild UP-TO-DATE
:react-native-sunmi-inner-scanner:preReleaseUnitTestBuild UP-TO-DATE
:react-native-sunmi-inner-scanner:prepareComAndroidSupportAppcompatV72301Library
:react-native-sunmi-inner-scanner:prepareComAndroidSupportSupportV42301Library
:react-native-sunmi-inner-scanner:prepareComFacebookFbuiTextlayoutbuilderTextlayoutbuilder100Library
:react-native-sunmi-inner-scanner:prepareComFacebookFrescoDrawee101Library
:react-native-sunmi-inner-scanner:prepareComFacebookFrescoFbcore101Library
:react-native-sunmi-inner-scanner:prepareComFacebookFrescoFresco101Library
:react-native-sunmi-inner-scanner:prepareComFacebookFrescoImagepipeline101Library
:react-native-sunmi-inner-scanner:prepareComFacebookFrescoImagepipelineBase101Library
:react-native-sunmi-inner-scanner:prepareComFacebookFrescoImagepipelineOkhttp3101Library
:react-native-sunmi-inner-scanner:prepareComFacebookReactReactNative0440Library
:react-native-sunmi-inner-scanner:prepareComFacebookSoloaderSoloader010Library
:react-native-sunmi-inner-scanner:prepareOrgWebkitAndroidJscR174650Library
:react-native-sunmi-inner-scanner:prepareReleaseDependencies
:react-native-sunmi-inner-scanner:compileReleaseAidl
:react-native-sunmi-inner-scanner:compileReleaseNdk UP-TO-DATE
:react-native-sunmi-inner-scanner:compileLint
:react-native-sunmi-inner-scanner:copyReleaseLint UP-TO-DATE
:react-native-sunmi-inner-scanner:compileReleaseRenderscript
:react-native-sunmi-inner-scanner:generateReleaseBuildConfig
:react-native-sunmi-inner-scanner:generateReleaseResValues
:react-native-sunmi-inner-scanner:generateReleaseResources
:react-native-sunmi-inner-scanner:mergeReleaseResources
:react-native-sunmi-inner-scanner:processReleaseManifest
:react-native-sunmi-inner-scanner:processReleaseResources
:react-native-sunmi-inner-scanner:generateReleaseSources
:react-native-sunmi-inner-scanner:incrementalReleaseJavaCompilationSafeguard
:react-native-sunmi-inner-scanner:compileReleaseJavaWithJavac
:react-native-sunmi-inner-scanner:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: /Users/edz/workspace/react-native/react-native-sunmi-inner-scanner-master/examples/node_modules/react-native-sunmi-inner-scanner/android/src/main/java/com/sunmi/scanner/SunmiInnerScannerModule.java使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
:react-native-sunmi-inner-scanner:extractReleaseAnnotations
:react-native-sunmi-inner-scanner:mergeReleaseShaders
:react-native-sunmi-inner-scanner:compileReleaseShaders
:react-native-sunmi-inner-scanner:generateReleaseAssets
:react-native-sunmi-inner-scanner:mergeReleaseAssets
:react-native-sunmi-inner-scanner:mergeReleaseProguardFiles
:react-native-sunmi-inner-scanner:packageReleaseRenderscript UP-TO-DATE
:react-native-sunmi-inner-scanner:packageReleaseResources
:react-native-sunmi-inner-scanner:processReleaseJavaRes UP-TO-DATE
:react-native-sunmi-inner-scanner:transformResourcesWithMergeJavaResForRelease
:react-native-sunmi-inner-scanner:transformClassesAndResourcesWithSyncLibJarsForRelease
:react-native-sunmi-inner-scanner:mergeReleaseJniLibFolders
:react-native-sunmi-inner-scanner:transformNative_libsWithMergeJniLibsForRelease
:react-native-sunmi-inner-scanner:transformNative_libsWithSyncJniLibsForRelease
:react-native-sunmi-inner-scanner:bundleRelease
:app:prepareComAndroidSupportAppcompatV72301Library
:app:prepareComAndroidSupportSupportV42301Library
:app:prepareComFacebookFbuiTextlayoutbuilderTextlayoutbuilder100Library
:app:prepareComFacebookFrescoDrawee101Library
:app:prepareComFacebookFrescoFbcore101Library
:app:prepareComFacebookFrescoFresco101Library
:app:prepareComFacebookFrescoImagepipeline101Library
:app:prepareComFacebookFrescoImagepipelineBase101Library
:app:prepareComFacebookFrescoImagepipelineOkhttp3101Library
:app:prepareComFacebookReactReactNative0440Library
:app:prepareComFacebookSoloaderSoloader010Library
:app:prepareExamplesReactNativeSunmiInnerScannerUnspecifiedLibrary
:app:prepareOrgWebkitAndroidJscR174650Library
:app:prepareDebugDependencies
:app:compileDebugAidl
:app:compileDebugRenderscript
:app:generateDebugBuildConfig
:app:mergeDebugShaders
:app:compileDebugShaders
:app:generateDebugAssets
:app:mergeDebugAssets
:app:generateDebugResValues
:app:generateDebugResources
:app:mergeDebugResources
:app:bundleDebugJsAndAssets SKIPPED
:app:processDebugManifest
:app:processDebugResources
:app:generateDebugSources
:app:incrementalDebugJavaCompilationSafeguard
:app:compileDebugJavaWithJavac
:app:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
:app:compileDebugNdk UP-TO-DATE
:app:compileDebugSources
:app:transformClassesWithDexForDebug
Running dex in-process requires build tools 23.0.2.
For faster builds update this project to use the latest build tools.
:app:mergeDebugJniLibFolders
:app:transformNative_libsWithMergeJniLibsForDebug
:app:processDebugJavaRes UP-TO-DATE
:app:transformResourcesWithMergeJavaResForDebug
:app:validateSigningDebug
:app:packageDebug
:app:assembleDebug
:app:installDebug
Installing APK 'app-debug.apk' on 'V1 - 5.1' for app:debug
02:11:15 E/138150028: Error while uploading app-debug.apk : Unknown failure ([CDS]close[0])
Unable to install /Users/edz/workspace/react-native/react-native-sunmi-inner-scanner-master/examples/android/app/build/outputs/apk/app-debug.apk
com.android.ddmlib.InstallException: Failed to install all
        at com.android.ddmlib.SplitApkInstaller.install(SplitApkInstaller.java:89)
        at com.android.ddmlib.Device.installPackages(Device.java:904)
        at com.android.builder.testing.ConnectedDevice.installPackages(ConnectedDevice.java:137)
        at com.android.build.gradle.internal.tasks.InstallVariantTask.install(InstallVariantTask.java:134)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:228)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:621)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:604)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
        at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:153)
        at org.gradle.internal.Factories$1.create(Factories.java:22)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:150)
        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:98)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:92)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:92)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:99)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:48)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:173)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:239)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:212)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:205)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:55)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:36)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
:app:installDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:installDebug'.
> com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: Failed to install all

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 10.549 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

**Comment by Mrlonglong** [comment]
在您的examples项目下运行react-native run-android时报这个

**Comment by januslo** [comment]
你自己的apk可以装进去不？我发现小米的手机都认低版本的grade

发自我的 iPhone

**Comment by januslo** [comment]
你直接build 然后手动装一下

发自我的 iPhone
